# Generated by Django 4.0.2 on 2022-02-24 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests', models.IntegerField(max_length=200)),
                ('roomType', models.CharField(max_length=200)),
                ('beds', models.IntegerField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('accId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='base.accommodation', verbose_name='Accommodation')),
            ],
        ),
    ]
